// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./src/components/BaseHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProfileDropdown: typeof import('./src/components/user/ProfileDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimplePlayer: typeof import('./src/components/UI/players/SimplePlayer.vue')['default']
    UiButton: typeof import('./src/components/UI/UiButton.vue')['default']
    UiContainer: typeof import('./src/components/UI/UiContainer.vue')['default']
    UiInput: typeof import('./src/components/UI/forms/UiInput.vue')['default']
    VkLogo: typeof import('./src/components/UI/Icons/VkLogo.vue')['default']
  }
}
